db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"
  environment:
    RACK_ENV: production
    RAILS_ENV: production

web:
  build: .
  command: bundle exec puma -C config/puma.rb
  ports:
    - "3000:3000"
  links:
    - db
  volumes:
    - .:/lunchiatto
  environment:
    RACK_ENV: production
    RAILS_ENV: production
    SECRET_KEY_BASE:  7ec2d1b94f00fe9b82d7ab0cfb60daf826f70170f753743b748581eb6bd7dadf31815f0448945d4ec970be29ba41752d4fc988cd4fe5b18163c53df0d2367cb6
