db:
  image: postgres:9.4.1

mailcatcher:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"

bundle:
  image: busybox
  volumes:
    - /bundle
    - /lunchiatto/vendor/assets/components

web:
  build: .
  command: bundle exec puma -C config/puma.rb
  env_file: .env
  ports:
    - "3000:3000"
  links:
    - db
    - mailcatcher
  volumes_from:
    - bundle
  volumes:
    - .:/lunchiatto
