db:
  image: postgres:9.4.1

redis:
  image: redis:3.0.5

sidekiq: &sidekiq
  build: .
  dockerfile: Dockerfile::Prod
  command: bundle exec sidekiq -q default -q mailers
  env_file: .env
  links:
    - db
    - redis

web:
  <<: *sidekiq
  command: bundle exec puma -C config/puma.rb
  ports:
    - "3000:3000"
