db:
  image: postgres:9.4.1

bundle:
  image: busybox
  volumes:
    - /bundle

web_prod: &web_prod
  build: .
  command: ./bin/prod
  env_file: .env
  ports:
    - "3000:3000"
  links:
    - db
  volumes_from:
    - bundle

web_dev:
  <<: *web_prod
  volumes:
    - .:/lunchiatto
  command: ./bin/dev