db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"

bundle:
  image: busybox
  volumes:
    - /bundle

web: &web
  build: .
  env_file: .env
  ports:
    - "3000:3000"
  links:
    - db
  volumes_from:
    - bundle

web_prod:
  <<: *web
  command: ./bin/prod

web_dev:
  <<: *web
  volumes:
    - .:/lunchiatto
  command: ./bin/dev