db:
  image: postgres:9.4.1

bundle:
  image: busybox
  volumes:
    - /bundle

web:
  build: .
  command: ./bin/prod
  env_file: .env
  ports:
    - "3000:3000"
  links:
    - db
  volumes_from:
    - bundle
