development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: codequest_manager_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: codequest_manager_test
  pool: 5
  username: postgres
  password: postgres
